services:
  - type: web
    name: job-flask-app-service
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /login
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: ADMIN_LOGIN_ID
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ADMIN_DISPLAY_NAME
        value: 管理者
